-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.2.446
-- Module  Version: 7.5
-- Sat May 16 15:30:21 2020

-- parameterized module component declaration
component RAM
    port (Clock: in  std_logic; ClockEn: in  std_logic; 
        Reset: in  std_logic; WE: in  std_logic; 
        Address: in  std_logic_vector(7 downto 0); 
        Data: in  std_logic_vector(15 downto 0); 
        Q: out  std_logic_vector(15 downto 0));
end component;

-- parameterized module component instance
__ : RAM
    port map (Clock=>__, ClockEn=>__, Reset=>__, WE=>__, Address(7 downto 0)=>__, 
        Data(15 downto 0)=>__, Q(15 downto 0)=>__);
